# Project: hw01_2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = "../C108110149\ hw01_1/main.o"
LINKOBJ  = "../C108110149 hw01_1/main.o"
LIBS     = -L"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = hw01_2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"../C108110149\ hw01_1/main.o": ../C108110149\ hw01_1/main.c
	$(CC) -c "../C108110149 hw01_1/main.c" -o "../C108110149 hw01_1/main.o" $(CFLAGS)
