# Project: hw01_3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = hw01_3.o
LINKOBJ  = hw01_3.o
LIBS     = -L"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/towel/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = hw01_3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

hw01_3.o: hw01_3.c
	$(CC) -c hw01_3.c -o hw01_3.o $(CFLAGS)
